version: '3.7'

services:

  php:
    image: php:7.4-fpm
    container_name: php-7.4
    restart: unless-stopped
    volumes: 
      - ./www:/var/www/html
  
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports: 
      - 80:80
    volumes: 
      - ./config/nginx:/etc/nginx/conf.d
      - ./www:/var/www/html